/*
 * Copyright 2014, NICTA
 *
 * This software may be distributed and modified according to the terms of
 * the BSD 2-Clause license. Note that NO WARRANTY is provided.
 * See "LICENSE_BSD2.txt" for details.
 *
 * @TAG(NICTA_BSD)
 */

#ifndef _CAMKES_DATAPORT_H_
#define _CAMKES_DATAPORT_H_

#include <stdint.h>
#include <sys/types.h>
#include <utils/util.h>

typedef char Buf[PAGE_SIZE_4K];

/* This type is intended to be used opaquely by a user. */
typedef struct dataport_ptr_ {
    uint32_t id;
    off_t offset;
} dataport_ptr_t;

/* These functions are generated by the CAmkES platform compilation, but are
 * intended to be invoked by the user.
 */
dataport_ptr_t dataport_wrap_ptr(void *ptr);
void *dataport_unwrap_ptr(dataport_ptr_t ptr);

#endif
