#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

# Generated by ckeywords.c. Do not edit manually.

from __future__ import absolute_import, division, print_function, \
    unicode_literals
from camkes.internal.seven import cmp, filter, map, zip

# A list of C keywords for the purpose of warning the user when a symbol in
# their input specification is likely to cause compiler errors.
C_KEYWORDS = frozenset([
    'auto', 'break', 'case', 'char', 'const', 'continue', 'default', 'do',
    'double', 'else', 'enum', 'extern', 'float', 'for', 'goto', 'if', 'inline',
    'int', 'long', 'register', 'restrict', 'return', 'short', 'signed',
    'sizeof', 'static', 'struct', 'switch', 'typedef', 'union', 'unsigned',
    'void', 'volatile', 'while', '_Alignas', '_Alignof', '_Atomic', '_Bool',
    '_Complex', '_Generic', '_Imaginary', '_Noreturn', '_Static_assert',
    '_Thread_local', '__func__', '__objc_yes', '__objc_no', 'asm', '_Bool',
    'wchar_t', '_Decimal32', '_Decimal64', '_Decimal128', '__alignof',
    '__attribute', '__builtin_choose_expr', '__builtin_offsetof',
    '__builtin_types_compatible_p', '__builtin_va_arg', '__extension__',
    '__imag', '__int128', '__label__', '__real', '__thread', '__FUNCTION__',
    '__PRETTY_FUNCTION__', 'typeof', '__private_extern__',
    '__module_private__', '__declspec', '__cdecl', '__stdcall', '__fastcall',
    '__thiscall', '__vectorcall', '__pascal', '__fp16', '__alignof__', '__asm',
    '__asm__', '__attribute__', '__complex', '__complex__', '__const',
    '__const__', '__imag__', '__inline', '__inline__', '__real__',
    '__restrict', '__restrict__', '__signed', '__signed__', '__typeof',
    '__typeof__', '__volatile', '__volatile__', '__builtin_convertvector',
    '__unknown_anytype',
])
