#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

# This library contains no files and exists only to pacify legacy applications that expect to link
# against it.

# Targets
TARGETS := libsel4muslccamkes.a

# Source files required to build the target
CFILES :=

# Header files/directories this library provides
HDRFILES :=

include $(SEL4_COMMON)/common.mk
